from . import inline_maga_30
from . import inline_maga_33
from . import inline_maga_38
from . import inline_maga_39
from . import inline_maga_40
from . import inline_maga_44
from . import inline_maga_48
from . import inline_maga_54
from . import inline_maga_56
from . import inline_maga_63
from . import inline_maga_65
from . import inline_maga_66
from . import inline_maga_67
from . import inline_maga_68
from . import inline_maga_74
from . import inline_maga_78
from . import inline_maga_79
from . import inline_maga_80
from . import inline_maga_83
from . import inline_maga_84
from . import inline_maga_89
from . import inline_maga_92