from . import choice_buttons
from . import Fidback_inline
from . import cansel_write
from . import cansel_posting
from . import inline_adm
from . import ikt_fiz_inline
from . import khem_inline
from . import sosity_inline
from . import Bachelor_course_inline
from . import degree_inline