from . import choice_buttons
from . import Fidback_inline
from . import inline_adm
from . import ikt_fiz_inline
from . import khem_inline
from . import Bachelor_course_inline
from . import degree_inline
from . import distans_ikt_inline
from . import midle_school_inline
from . import end_yep_inline