from . import button_maga_main
from . import maga_30_but
from . import maga_33_but
from . import maga_38_but
from . import maga_39_but
from . import maga_40_but
from . import maga_44_but
from . import maga_48_but
from . import maga_54_but
from . import maga_56_but
from . import maga_63_but
from . import maga_65_but
from . import maga_66_but
from . import maga_67_but
from . import maga_68_but
from . import maga_74_but
from . import maga_78_but
from . import maga_79_but
from . import maga_80_but
from . import maga_83_but
from . import maga_84_but
from . import maga_89_but
from . import maga_92_but